
<?php

return [
    "head"      => "Protección de datos y privacidad",
    "general.1" => "Protección de datos y privacidad son para nosotros los bienes más importantes del internet. Son dignos de ser protegidos y no se debería usarlos comercialmente. Aquí una corta lista de nuestro modo de proceder. Una extensa presentación con información trasfondo, porque nosotros mantenemos el único buscador realmente seguro, encuentra en <a href=\"https://suma-ev.de/presse/Sicher-suchen-UND-finden-mit-MetaGer.html\">aquí.</a> ",
    "general.3" => "Solo software que esta libre y el código fuente disponible, puede ser revisado por cualquier persona. En los demás casos el usuario tiene que CREER, lo que dice la compañía operadora o el vendedor del sello de calidad. MetaGer es software libre bajo licencia GNU-AGPLv3 (vea la noticia relacionada en alemán en el Heise Ticker <a href=\"http://heise.de/-3295586\" target=\"_blank\" rel=\"noopener\">http://heise.de/-3295586</a>). Usted puede descargar el código fuente de MetaGer aquí: <a href=\"https://gitlab.metager3.de/open-source/MetaGer\" target=\"_blank\" rel=\"noopener\">https://gitlab.metager3.de/open-source/MetaGer</a><br /> No necesita creernos nada: USTED mismo lo puede controlar!",
    "policy.1"  => "Nuestro procedimiento / política:",
    "policy.2"  => "No guardamos su numero IP, ni <a href=\"https://amiunique.org/\" target=\"_blank\" rel=\"noopener\">la huella digital de su navegador</a> (con lo cual usted muy probablemente esta identificable).",
    "policy.5"  => "No usamos Cookies o un Tracking-Pixel o tecnologías similares, para perseguir a nuestros usuarios (Tracking = Seguir los movimientos en el internet).",
    "policy.6"  => "La transmisión de datos en MetaGer se hace únicamente cifrado con el protocolo https.",
    "policy.7"  => "Ofrecemos un acceso sobre la red anónimo TOR, el <a href=\"http://forum.suma-ev.de/viewtopic.php?f=3&t=43&sid=c994b628153235dfef098ba6fea3d60e\" target=\"_blank\" rel=\"noopener\">MetaGer-TOR-hidden Service.</a>",
    "policy.9"  => "Porque el acceso sobre la red TOR les parece a muchos usuarios complicado, aveces esta lento, nosotros hemos implementado un camino alterno, con lo cual puede llegar hasta las páginas de destino guardando su anonimato : Haciendo click en el link \"abrir anónimo\". Mediante esto sus datos personales están protegidos al hacer click sobre resultados en MetaGer y incluso en todos los clicks que siguen.",
    "policy.10" => "Hacemos muy poca publicidad, la marcamos claramente, y confiamos para nuestra financiación en nuestros usuarios, sus <a href=\"/spende/\">donaciones</a> y membresías para el  <a href=\"http://suma-ev.de/\" target=\"_blank\" rel=\"noopener\">SUMA-EV</a>. ",
    "policy.13" => "La organización sin fines de lucro <a href=\"http://suma-ev.de/\" target=\"_blank\" rel=\"noopener\">SUMA-EV</a> en cooperación con la <a href=\"http://www.uni-hannover.de/\" target=\"_blank\" rel=\"noopener\">Leibniz Universität Hannover</a>  mantienen y desarrollan MetaGer. ",
    "policy.17" => "Nuestros servidores están exclusivamente en Alemania. Estan bajo de la ley de protección de datos alemán, lo cual es considerado uno de los más estrictos del mundo.",
    "policy.18" => "No solamente protegemeos suyos datos, pero el ambiente. Llevamos nuestros servidores con electricidad verde.",
    "policy.19" => "Después de las revelaciones de Edward Snowden en Junio 2013 se han posicionado varios buscadores con la autoproclamación que sus búsquedas estuvieron seguras porque no guardan los IP de los usuarios. Suponiendo honestos intensiones en estos autodescripciones, es un hecho que muchos de estos buscadores hostean al menos una parte de sus servidores en EEUU. Esto incluye algunos que aun están recomendados por protectores de datos. Estos buscadores están<a href=\"http://de.wikipedia.org/wiki/USA_PATRIOT_Act\" target=\"_blank\" rel=\"noopener\"> bajo de la ley Patriot Act y bajo derecho de EEUU y las autoridades tienen acceso completo a la data</a> y por ende no puede garantizar la privacidad de sus usuarios (a pesar de los esfuerzos de ellos mismos).",
    "twitter"   => "Lo que otros dicen sobre nuestro concepto de privacidad en Twitter:",
];